name: Build and deploy ASP.Net Core app to Azure Web App - fake-it-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./FakeIt.Web/FakeIt.Web.csproj  # Relative path to the project file

      - name: Build the project
        run: dotnet build ./FakeIt.Web/FakeIt.Web.csproj --configuration Release --no-restore  # Relative path to the project file

      - name: Publish the project to myapp directory
        run: dotnet publish ./FakeIt.Web/FakeIt.Web.csproj -c Release -o ${{ github.workspace }}/myapp  # Use GitHub workspace for output

      - name: List files in myapp
        run: ls -R ${{ github.workspace }}  # Check if files are correctly placed in the 'myapp' directory

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: fake-it-app
          path: ${{ github.workspace }}  # Upload the 'myapp' directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for JWT requests

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: fake-it-app  # Match the uploaded artifact name

      - name: List downloaded files
        run: ls -R ${{ github.workspace }}/myapp  # Verify the 'myapp' directory exists after download

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fake-it-app'
          slot-name: 'Production'
          package: ${{ github.workspace }}  # Use the correct path for deployment
