# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - fake-it-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ../FakeIt.Web.sln  # Specify the relative path to your solution file

      - name: Build with dotnet
        run: dotnet build ../FakeIt.Web.sln --configuration Release  # Specify the relative path to your solution file

      - name: dotnet publish
        run: dotnet publish ../FakeIt.Web.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp  # Specify the relative path to your solution file

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_138EE918B28E4479B57894C142584C19 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ECF2B5C54AC1444F881EF2E216E8EC10 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D031A483B9144A80B384429A6E9BFF34 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fake-it-app'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp  # Point to the published output directory
